include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # dart 3.8 이후 추가된 collection-null-safety 관련 린트 추가
    use_null_aware_elements: true
    # 항상 상대경로로 import 하도록 강제 (Dart 가이드에 따라서 같은 프로젝트의 import는 상대경로 사용 권장)
    prefer_relative_imports: true

formatter:
  trailing_commas: preserve
